import Head from 'next/head'
import Image from 'next/image'

import styles from 'styles/Home.module.css'

import explosion from 'design/avatar-image/AvatarPhotos/Chill-2.png'
import SectionContainer from 'components/SectionContainer'

export default function Home () {
  return (
    <>
      <Head>
        <title>Alan Valencia</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.home}>
        <SectionContainer className={styles.slider}>
          <div className={styles['content-images-slider']}>
            <div className={styles['image-slider']}>
              <Image src={explosion} alt='' fill />
            </div>
            <div className={styles['text-slider']}>
              <h1 className={styles['slider-text']}>
                Hi, I&apos;m Alan Smith Valencia Izquierdo
              </h1>
            </div>
          </div>
        </SectionContainer>
        <SectionContainer>
          <h2 className={styles.title}>Hello world</h2>
        </SectionContainer>
      </main>
    </>
  )
}
