import SectionContainer from 'components/SectionContainer'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from 'styles/Home.module.css'
import explosion from 'design/avatar-image/AvatarPhotos/Chill-2.png'

import { GoMarkGithub } from 'react-icons/go'
import { BsLinkedin } from 'react-icons/bs'

export default function Home () {
  return (
    <>
      <Head>
        <title>Alan Valencia</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.home}>
        <SectionContainer className={styles.slider}>
          <div className={styles['content-images-slider']}>
            <div className={styles['image-slider']}>
              <Image src={explosion} alt='' fill />
            </div>
            <div className={styles['text-slider']}>
              <div></div>
              <div>
                <div className={styles['slider-text']}>
                  <div></div>
                  <div>
                    <div className={styles['s-text']}>
                      <h1>Hello, I&apos;m Alan Smith Valencia Izquierdo</h1>
                    </div>
                  </div>
                  <div className={styles.links}>
                    <div className={styles['s-links']}>
                      <Link href='/contact' legacyBehavior>
                        <a>
                          <GoMarkGithub />
                        </a>
                      </Link>
                      <Link href='/contact' legacyBehavior>
                        <a>
                          <BsLinkedin />
                        </a>
                      </Link>
                    </div>
                    <div>
                      <Link href='/project' className={styles['p-link']}>
                        All Projects
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </SectionContainer>
        <SectionContainer f_direction='column'>
          <h2 className={styles.title}>
            FEATURED
          </h2>
          <h2 className={styles.title}>
            PROJECTS
          </h2>
        </SectionContainer>
      </main>
    </>
  )
}
